version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=kennel_db
      - DATABASE_USER=kennel_user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: kennel_db
      POSTGRES_USER: kennel_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
