

services:
  backend:
    build:
      context: ./kennel_manager_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=kennel_db
      - DATABASE_USER=kennel_user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432  # Use default port 5432
    networks:
      - kennel-network

  frontend:
    build:
      context: ./kennel_manager_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    networks:
      - kennel-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kennel_db
      POSTGRES_USER: kennel_user
      POSTGRES_PASSWORD: password
    ports:
      - "5454:5432"  # Map default port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kennel-network

networks:
  kennel-network:

volumes:
  postgres_data:
